version: '3.8'

services:
  backend:
    build: .
    environment:
      - MONGO_URI=mongodb+srv://InnoWave:PxEU801XfPNlpmND@cluster0.zekb51t.mongodb.net/InnoWave?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=innowave-jwt-secret-123454321
      - JWT_COOKIE_NAME=innowavejwt
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
